gui:
  theme:
    selectedLineBgColor:
      - "#1A53AC"
  nerdFontsVersion: 3
os:
  editPreset: "vim"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
